on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set-up OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 5
          opam-repositories: |
            rocq-released: https://rocq-prover.org/opam/released
            default: https://github.com/ocaml/opam-repository.git

      - name: Install rocq
        run: opam install -y rocq-prover

      - name: Build project
        run: |
          opam exec -- ./configure.sh
          opam exec -- make
